contact_links:
  - name: ðŸ’¬ General Questions
    url: https://github.com/LostMinions/discussions
    about: Ask questions or start an open discussion.
  - name: ðŸ§µ Shop Support
    url: https://www.etsy.com/shop/LostMinions
    about: For questions about prints, orders, or commissions.
